version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4500:4500"
    volumes:
      - ./index.php:/usr/share/nginx/html/index.php
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Senha123
      MYSQL_DATABASE: meubanco
    volumes:
      - db_data:/var/lib/mysql
      - ./banco.sql:/docker-entrypoint-initdb.d/banco.sql

volumes:
  db_data:
